-- create DDL for bronze table
CREATE TABLE bronze.superstore (
    category varchar,
    city varchar,
    country varchar,
    customer_id varchar,
    customer_name varchar,
    discount numeric,
    market varchar,
    order_date timestamptz,
    order_id varchar,
    order_priority varchar,
    product_id varchar,
    product_name varchar,
    profit numeric,
    quantity numeric,
    region varchar,
    row_id varchar,
    sales numeric,
    segment varchar,
    shipdate timestamptz,
    ship_mode varchar,
    shipping_cost numeric,
    state varchar,
    sub_category varchar,
    year numeric,
    market2 varchar,
    weeknum numeric
);
